services:
  nodejs:
    container_name: nodejs
    image: nodejs
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
      DEPLOYMENT_TYPE: ${DEPLOYMENT_TYPE}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
    restart: always
    volumes:
      - ./downloads:/usr/src/app/downloads
